import type { Metadata } from "next";
import "./globals.css";
import Header from "@web/components/Header";

export const metadata: Metadata = {
	title: "SYA, votre assistant web",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body className={`antialiased`}>
				<Header />

				<main className="bg-zinc-900 text-gray-200">{children}</main>
			</body>
		</html>
	);
}
