[package]
name = "api"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
base64ct = "=1.7.3"
actix-web = "4"
actix-cors = "0.6"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
once_cell = "1.18.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono"] }
jsonwebtoken = "9"
argon2 = "0.5"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
rand_core = "0.6"
tracing = "0.1"
anyhow = "1"
rand = "0.9.2"

[dev-dependencies]
httpmock = "0.7"
serial_test = "2.0"

[[bin]]
name = "api"
path = "src/main.rs"
